# Generated by Django 2.2.8 on 2020-01-07 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Задача')),
                ('perfomer', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Roman'), (2, 'Ivan'), (3, 'Ivanh'), (4, 'Ivanhd'), (5, 'Ivanhdhk'), (6, 'Ivanhdhkd'), (7, 'I'), (8, 'Idd'), (9, 'Iddd'), (10, 'Idddds'), (11, 'sdsd'), (12, 'Romans')], verbose_name='Исполнитель')),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
