# Generated by Django 2.2.8 on 2020-01-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200107_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='perfomer',
        ),
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.CharField(blank=True, max_length=25, verbose_name='Исполнитель'),
        ),
    ]
